name: Practise with artifact
on:
  push:
    branches:
      - main

env:
  FILE_NAME: artifact-test

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create ${{env.FILE_NAME}}
        uses: actions/checkout@v3
         run: touch ${{env.FILE_NAME}}.md
      
      - name: Upload artifact
        uses: actions/upload-artifact
        with:
          name: test
          path: ./${{env.FILE_NAME}}
      
