name: Artifact
on:
  push:
    branches:
      - master

env:
  FILE_NAME: artifact-test

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v2

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: .
      
