name: Artifact
on:
  push:
    branches:
      - main

env:
  FILE_NAME: artifact-test

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out code
        uses: actions/checkout@v2

      - name: Add expr to file
        run: expr 1 + 1 > outputfile.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output  #Create a directory with the name output and store the file outputfile.txt in it
          path: outputfile.txt

      - name: print success
        if: ${{success()}}
        run: echo 'Succesfully executed the previous tasks'

  download-artifact:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: output

      - name: print output
        run: cat output/outputfile.txt      
