name: Test
on: 
  push:
    branches:
      - "main"

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.1"

      - name: install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test 


  show-changes:
    runs-on: ubuntu-latest
    needs: test
    if: ${{failure()}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: File Changes Action
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          fileOutput: 'json'

      - name: Show file Changes
        run: |
         cat $HOME/files.json
         cat $HOME/files_added.json
         cat $HOME/files_modified.json
         cat $HOME/files_removed.json
         cat $HOME/files_renamed.json


  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{success()}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - run: echo "Attempting to deploy"