name: Test
on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.1"

      - name: install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  show-changes:
    runs-on: ubuntu-latest
    needs: test
    if: ${{failure()}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: File Changes Action
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          fileOutput: "json"

      - name: Show file Changes
        run: |
          printf "All files\n"
          cat $HOME/files.json

          printf "\n\nAdded files\n"
          cat $HOME/files_added.json

          printf "\n\nModified files\n"
          cat $HOME/files_modified.json

          printf "\n\nRemoved files\n"
          cat $HOME/files_removed.json

          printf "\n\nRenamed files\n"
          cat $HOME/files_renamed.json

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{success()}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "github-actions-practise"
          heroku_email: "kailashbb12@hotmail.com"

      - name: Succesful deployment
        if: ${{success()}}
        run: echo "Succesful deployment"

      - name: Failed deployment
        if: ${{failure()}}
        run: echo "Failed deployment"
