name: Test
on: 
  push:
    branches:
      - "main"

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.1"

      - name: install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test 


  show-changes:
    runs-on: ubuntu-latest
    needs: test
    if: ${{failure()}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: File Changes Action
        uses: trilom/file-changes-action@v1.2.4

      - name: Show file Changes
        run: ls .


  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{success()}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - run: echo "Attempting to deploy"